baseURL = "https://www.burakaltundal.com/"
languageCode = "en-us"
title = "Burak Altundal"
enableRobotsTXT = true
paginate = 10
summaryLength = 10
googleAnalytics = "" 
publishDir = "docs"

[taxonomies]
  category = "kategori"
  tag = "etiket"

[author]
	name = "buyucu"

[params]
  author = "Burak Altundal"
  description = "Burak Altundal | büyücü"
	alias = "büyücü"
  images = ["buyucu.png"]

  showReadMore = true
  email = "burak.altundal@gmail.com"
  twitter = "baltundal"
  instagram = "buyucu"

  # Programming
  github = "altundal"
	mainSections = ["gunceler","yazilar","siirler","mektuplar"]

# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "kim"
	name = "Kim?"
	url = "/kim/"
	weight = 3

[[menu.main]]
	identifier = "kategori"
	name = "Kategoriler"
	url = "/kategori/"
	weight = 1
